build:
  version: "1.0"

accounts:
  message: "Welcome to South Dragon Bank Accounts related prod APIs"
  contactDetails:
    name: "South Dragon PO- Product Owner"
    email: "tnamlong2132000@gmail.com"
  onCallSupport:
    - 0987654321
    - 1102031923

