server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "accounts"
    description: "South Dragon Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      southdragon:
        accounts: DEBUG